### ISSUE TITLE
Installing mentioned dependencies on Arch Linux

### ISSUE THREAD

**Issue by nottherealtar** [Rayrsn/Dank-Memer-Grinder#1]
Is there anyway i can get this to run on arch linux ? i've tried installing the mentioned dependencies : 
gir1.2-wnck-3.0 gobject PyGObject

but none of which are availaible or found..

**Comment by nottherealtar** [comment]
and thanks for making this, much needed !

**Comment by Rayrsn** [comment]
what is your desktop environment?

**Comment by nottherealtar** [comment]
> what is your desktop environment?

Garuda Linux, so i'm using an arch distro

**Comment by nottherealtar** [comment]
I have tried manually going to arch community and finding the packages or even pacman the packages but no luck so far. Im pretty new to this so any help would be appreciated. I promise i tried xD not trying to just leech

**Comment by Rayrsn** [comment]
i'm gonna test the script on my own Garuda, i'll update you.

**Comment by Rayrsn** [comment]
***Updated readme***

You have to install wnck3 you can do that on Arch-based distros by running 
```bash 
sudo pacman -S libwnck3
```
